export const BUILDING_TEXTS: Record<string, { flavor: string; details: string }> = {
    town_hall: { flavor: "The heart of the village.", details: "Protects resources. Losing this grants the enemy a victory star." },
    cannon: { flavor: "Keep the fuse dry.", details: "A basic point defense. Fires heavy cast iron balls at ground targets." },
    barracks: { flavor: "Discipline and glory.", details: "Upgrade to unlock new troop types for your army." },
    lab: { flavor: "Knowledge is power.", details: "Researches troop upgrades. Boosts HP, damage, speed, and range for all troops." },
    army_camp: { flavor: "Rest and recover.", details: "Provides housing space for your army. Upgrade to field more troops." },
    wall: { flavor: "Good fences.", details: "A simple barrier to slow down ground troops. Directs enemy flow." },
    mortar: { flavor: "Incoming!", details: "Lobs explosive shells with splash damage. Ineffective at close range, deadly at long range." },
    ballista: { flavor: "Precision engineering.", details: "Launches heavy bolts. Deals extreme damage to single targets." },
    xbow: { flavor: "Supersonic.", details: "Rapid-fire crossbow. Overwhelms enemies with a hail of bolts." },
    tesla: { flavor: "Shocking.", details: "Hidden underground. Pops up to zap up to 3 enemies with chain lightning." },
    prism: { flavor: "Focused light.", details: "Channels a continuous laser beam. Deals ramping damage to a single target." },
    dragons_breath: { flavor: "Ancient fury.", details: "A massive battery of 16 firecracker pods. Rains down a staggered salvo of explosive fire." },
    spike_launcher: { flavor: "Step lightly.", details: "Hurls a spiked ball that carpets the ground in caltrops, wounding everything that walks through." },
    frostfall: { flavor: "Winter, bottled.", details: "A crystal engine that chills attackers, slowing their advance to a crawl." },
    mine: { flavor: "The night shift never ends.", details: "Miners dig ore around the clock. Ore pays for your upgrades." },
    farm: { flavor: "An army marches on its stomach.", details: "Grows food to feed your growing population." },
    storage: { flavor: "Full shelves, calm nerves.", details: "Raises how much ore and food your village can keep on hand." },
};
