export const BUILDING_TEXTS: Record<string, { flavor: string; details: string }> = {
    town_hall: { flavor: "The heart of the village.", details: "Protects resources. Losing this grants the enemy a victory star." },
    cannon: { flavor: "Keep the fuse dry.", details: "A reliable point defense. Fires heavy cast iron balls at nearby attackers." },
    barracks: { flavor: "Gears before glory.", details: "The Mechanica Barracks advances the Steampunk troop tree, one unit per level." },
    mystic_barracks: { flavor: "Power answers preparation.", details: "The Mystic Barracks advances the Magic troop tree, one new discipline per level." },
    lab: { flavor: "Knowledge is power.", details: "Researches troop upgrades. Boosts HP, damage, and healing without changing combat reach or timing." },
    army_camp: { flavor: "Rest and recover.", details: "Provides housing and unlocks Barbarian, Archer, Healer, and Phalanx from levels 1 through 4." },
    wall: { flavor: "Good fences.", details: "A simple barrier to slow down ground troops. Directs enemy flow." },
    mortar: { flavor: "Incoming!", details: "Lobs explosive shells with splash damage. Ineffective at close range, deadly at long range." },
    ballista: { flavor: "Precision engineering.", details: "Launches heavy bolts. Deals extreme damage to single targets." },
    xbow: { flavor: "Supersonic.", details: "Rapid-fire crossbow. Overwhelms enemies with a hail of bolts." },
    tesla: { flavor: "Shocking.", details: "Hidden underground. Pops up to zap up to 3 enemies with chain lightning." },
    prism: { flavor: "Focused light.", details: "Channels a continuous laser beam. Steadily melts a single target for as long as it holds the lock." },
    dragons_breath: { flavor: "Ancient fury.", details: "A massive battery of 16 firecracker pods. Rains down a staggered salvo of explosive fire." },
    spike_launcher: { flavor: "Step lightly.", details: "Hurls a spiked ball that carpets the ground in caltrops, wounding everything that walks through." },
    jukebox: { flavor: "Every village needs a song.", details: "Plays your collected tracks. Rare tunes are out there — earn them by playing." },
    watchtower: { flavor: "Eyes on the horizon.", details: "Reveals the world beyond your fences. Upgrade to see the whole horizon." },
    mine: { flavor: "The night shift never ends.", details: "Miners dig ore around the clock. Ore pays for your upgrades." },
    farm: { flavor: "An army marches on its stomach.", details: "Grows food to feed your growing population." },
    storage: { flavor: "Full shelves, calm nerves.", details: "Raises how much ore and food your village can keep on hand." },
};
